version: "3.9"

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: paraform_zoom
      POSTGRES_USER: paraform_zoom
      POSTGRES_DB: paraform_zoom

  app:
    build:
      context: ./
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"